/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixedRouteImport } from './routes/fixed'
import { Route as FoundRouteImport } from './routes/found'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as UnderstandRouteImport } from './routes/understand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedRoute = FixedRouteImport.update({
  id: '/fixed',
  path: '/fixed',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixed': typeof FixedRoute
  '/found': typeof FoundRoute
  '/ready': typeof ReadyRoute
  '/scan': typeof ScanRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixed': typeof FixedRoute
  '/found': typeof FoundRoute
  '/ready': typeof ReadyRoute
  '/scan': typeof ScanRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixed': typeof FixedRoute
  '/found': typeof FoundRoute
  '/ready': typeof ReadyRoute
  '/scan': typeof ScanRoute
  '/understand': typeof UnderstandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixed' | '/found' | '/ready' | '/scan' | '/understand'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixed' | '/found' | '/ready' | '/scan' | '/understand'
  id:
    '__root__' | '/' | '/fixed' | '/found' | '/ready' | '/scan' | '/understand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixedRoute: typeof FixedRoute
  FoundRoute: typeof FoundRoute
  ReadyRoute: typeof ReadyRoute
  ScanRoute: typeof ScanRoute
  UnderstandRoute: typeof UnderstandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed': {
      id: '/fixed'
      path: '/fixed'
      fullPath: '/fixed'
      preLoaderRoute: typeof FixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixedRoute: FixedRoute,
  FoundRoute: FoundRoute,
  ReadyRoute: ReadyRoute,
  ScanRoute: ScanRoute,
  UnderstandRoute: UnderstandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
